'use client';

import { Project, ContextOfUseCard, NAMStudy, EvidenceItem, ClaimNode, ECTDMapping } from '@/lib/types';
import { Download, FileJson, FileText, FileSpreadsheet, FolderTree, AlertTriangle, CheckCircle } from 'lucide-react';

interface ExportCenterProps {
  project: Project;
  cou: ContextOfUseCard;
  study: NAMStudy;
  evidenceItems: EvidenceItem[];
  claimNodes: ClaimNode[];
  ectdMappings: ECTDMapping[];
}

function buildJSONPackage(props: ExportCenterProps): string {
  return JSON.stringify(
    {
      package_id: `PKG-${props.project.id}-${Date.now()}`,
      schema_version: '1.0.0',
      tool: 'NAMO-to-IND Mapper',
      exported_at: new Date().toISOString(),
      project: props.project,
      context_of_use: props.cou,
      nam_study: props.study,
      evidence_matrix: props.evidenceItems,
      claim_nodes: props.claimNodes,
      ectd_mappings: props.ectdMappings,
    },
    null,
    2
  );
}

function buildCSV(items: EvidenceItem[]): string {
  const header = ['Evidence ID', 'Domain', 'Question', 'Evidence Type', 'Status', 'Notes', 'Supporting Data'];
  const rows = items.map((i) => [
    i.evidence_id,
    i.domain,
    `"${i.question.replace(/"/g, '""')}"`,
    `"${i.evidence_type.replace(/"/g, '""')}"`,
    i.status,
    `"${i.notes.replace(/"/g, '""')}"`,
    `"${(i.supporting_data ?? '').replace(/"/g, '""')}"`,
  ]);
  return [header.join(','), ...rows.map((r) => r.join(','))].join('\n');
}

function buildMarkdown(props: ExportCenterProps): string {
  const { project, cou, study, evidenceItems, claimNodes, ectdMappings } = props;
  const lines: string[] = [];

  lines.push(`# NAM Evidence Dossier`);
  lines.push(`**Project:** ${project.name}  `);
  lines.push(`**Drug:** ${project.drug_name}  `);
  lines.push(`**Sponsor:** ${project.sponsor}  `);
  lines.push(`**Generated:** ${new Date().toUTCString()}  `);
  lines.push(`**Tool:** NAMO-to-IND Mapper v0.1.0  `);
  lines.push('');
  lines.push('---');
  lines.push('');

  lines.push('## 1. Context of Use');
  lines.push(`**COU ID:** ${cou.cou_id} (v${cou.version})  `);
  lines.push(`**NAM Type:** ${cou.nam_type}  `);
  lines.push(`**Regulatory Question:** ${cou.regulatory_question}  `);
  lines.push(`**Development Stage:** ${cou.drug_development_stage}  `);
  lines.push(`**Intended Use:** ${cou.intended_use}  `);
  lines.push(`**Biological Domain:** ${cou.biological_domain}  `);
  lines.push(`**Regulatory Confidence Level:** ${cou.regulatory_confidence_level}  `);
  lines.push('');
  lines.push('### Limitations');
  cou.limitations.forEach((l) => lines.push(`- ${l}`));
  lines.push('');
  lines.push('### Acceptance Criteria');
  cou.acceptance_criteria.forEach((a) => lines.push(`- ${a}`));
  lines.push('');

  lines.push('## 2. NAM Study Metadata');
  lines.push(`**Study ID:** ${study.study_id}  `);
  lines.push(`**Title:** ${study.title}  `);
  lines.push(`**Model System:** ${study.model_system.namo_class} (${study.model_system.cell_type})  `);
  lines.push(`**Species:** ${study.model_system.species}  `);
  lines.push(`**Tissue:** ${study.model_system.tissue_origin}  `);
  lines.push('');

  lines.push('## 3. Validation Evidence Matrix');
  lines.push('');
  lines.push('| ID | Domain | Status | Question |');
  lines.push('|----|--------|--------|----------|');
  evidenceItems.forEach((e) => {
    lines.push(`| ${e.evidence_id} | ${e.domain} | **${e.status}** | ${e.question} |`);
  });
  lines.push('');

  lines.push('## 4. Weight-of-Evidence Claims');
  claimNodes.forEach((c) => {
    lines.push(`### ${c.claim_id}`);
    lines.push(`**Confidence:** ${c.confidence}  `);
    lines.push(`**Review Status:** ${c.review_status}  `);
    lines.push('');
    lines.push(`> ${c.claim_text}`);
    lines.push('');
    if (c.limitations.length) {
      lines.push('**Limitations:**');
      c.limitations.forEach((l) => lines.push(`- ⚠ ${l}`));
      lines.push('');
    }
  });

  lines.push('## 5. eCTD Module 4 Placement');
  ectdMappings.forEach((m) => {
    lines.push(`### ${m.ectd_section} — ${m.ectd_title}`);
    lines.push(`**Evidence type:** ${m.evidence_type}  `);
    lines.push(m.notes);
    if (m.justification) lines.push(`*Rationale: ${m.justification}*`);
    lines.push('');
  });

  lines.push('---');
  lines.push('*Generated by NAMO-to-IND Mapper. This dossier is a tool output and requires human review before regulatory submission.*');

  return lines.join('\n');
}

function buildECTDFolderMap(props: ExportCenterProps): string {
  const lines: string[] = [];
  lines.push(`eCTD Module 4 Folder Map — ${props.project.drug_name}`);
  lines.push(`Generated: ${new Date().toUTCString()}`);
  lines.push('');
  lines.push('m4/');
  lines.push('├── 4.2-study-reports/');
  lines.push('│   └── 4.2.3-toxicology/');
  lines.push('│       └── 4.2.3.7-other-toxicology/');
  lines.push('│           └── 4.2.3.7.3-other-in-vitro/');
  lines.push(`│               ├── ${props.study.study_id}_study-report.pdf`);
  lines.push(`│               ├── ${props.study.study_id}_namo-metadata.json`);
  lines.push(`│               └── EVID-MATRIX-001_validation-evidence-matrix.csv`);
  lines.push('│');
  lines.push('m2/');
  lines.push('├── 2.6.2-pharmacology-written-summary/');
  lines.push(`│   └── CLAIM-GRAPH-001_woe-summary-excerpt.docx`);
  lines.push('└── 2.6.6-toxicology-written-summary/');
  lines.push(`    └── CLAIM-GRAPH-001_hepatotoxicity-woe-section.docx`);
  lines.push('');
  lines.push('--- Mapping Details ---');
  props.ectdMappings.forEach((m) => {
    lines.push(`[${m.ectd_section}] ${m.ectd_title}`);
    lines.push(`  Evidence: ${m.evidence_type}`);
    lines.push(`  Note: ${m.notes}`);
    lines.push('');
  });
  return lines.join('\n');
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ExportCenter(props: ExportCenterProps) {
  const { claimNodes } = props;
  const pendingClaims = claimNodes.filter((c) => c.review_status === 'human_review_required');
  const allApproved = pendingClaims.length === 0;

  const slug = props.project.drug_name.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();

  return (
    <div className="space-y-6">
      {/* Review gate */}
      <div className={`p-4 rounded-xl border ${allApproved ? 'bg-green-50 border-green-200' : 'bg-amber-50 border-amber-200'}`}>
        <div className="flex items-center gap-3">
          {allApproved ? (
            <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0" />
          ) : (
            <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0" />
          )}
          <div>
            <p className={`text-sm font-semibold ${allApproved ? 'text-green-800' : 'text-amber-800'}`}>
              {allApproved ? 'All claims approved — export enabled' : `Human review required for ${pendingClaims.length} claim(s)`}
            </p>
            <p className={`text-xs mt-0.5 ${allApproved ? 'text-green-700' : 'text-amber-700'}`}>
              {allApproved
                ? 'The evidence package is ready for export. Outputs are tool-generated and not a substitute for qualified regulatory review.'
                : `Review and approve all claims in the Claim Graph workspace before exporting. Pending: ${pendingClaims.map((c) => c.claim_id).join(', ')}`}
            </p>
          </div>
        </div>
      </div>

      {/* Export actions */}
      <div className="grid grid-cols-2 gap-4">
        {[
          {
            icon: FileJson,
            title: 'JSON Package',
            description: 'Complete machine-readable evidence package (project, COU, study, evidence matrix, claims, eCTD mappings)',
            format: 'JSON',
            color: 'border-blue-200 hover:border-blue-400',
            iconColor: 'text-blue-600',
            action: () =>
              downloadFile(
                buildJSONPackage(props),
                `${slug}_namo-evidence-package.json`,
                'application/json'
              ),
          },
          {
            icon: FileSpreadsheet,
            title: 'Validation Evidence Matrix',
            description: 'CSV export of all validation evidence items across all eight domains, suitable for regulatory submission appendix',
            format: 'CSV',
            color: 'border-green-200 hover:border-green-400',
            iconColor: 'text-green-600',
            action: () =>
              downloadFile(
                buildCSV(props.evidenceItems),
                `${slug}_validation-evidence-matrix.csv`,
                'text/csv'
              ),
          },
          {
            icon: FileText,
            title: 'Markdown Dossier',
            description: 'Human-readable evidence dossier in Markdown format — suitable for conversion to Word/PDF for regulatory review',
            format: 'MD',
            color: 'border-violet-200 hover:border-violet-400',
            iconColor: 'text-violet-600',
            action: () =>
              downloadFile(
                buildMarkdown(props),
                `${slug}_namo-evidence-dossier.md`,
                'text/markdown'
              ),
          },
          {
            icon: FolderTree,
            title: 'eCTD Module 4 Folder Map',
            description: 'Text representation of the proposed eCTD Module 4 folder structure with document placement rationale',
            format: 'TXT',
            color: 'border-amber-200 hover:border-amber-400',
            iconColor: 'text-amber-600',
            action: () =>
              downloadFile(
                buildECTDFolderMap(props),
                `${slug}_ectd-module4-folder-map.txt`,
                'text/plain'
              ),
          },
        ].map((item) => {
          const Icon = item.icon;
          return (
            <div key={item.title} className={`card p-5 border-2 transition-colors ${item.color}`}>
              <div className="flex items-start gap-4">
                <div className={`w-10 h-10 rounded-lg bg-slate-50 flex items-center justify-center flex-shrink-0`}>
                  <Icon className={`w-5 h-5 ${item.iconColor}`} />
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <h4 className="font-semibold text-slate-800 text-sm">{item.title}</h4>
                    <span className="badge bg-slate-100 text-slate-600 text-xs font-mono">{item.format}</span>
                  </div>
                  <p className="text-xs text-slate-500 leading-relaxed mb-3">{item.description}</p>
                  <button
                    className="btn-primary text-xs py-1.5"
                    onClick={item.action}
                    disabled={!allApproved}
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download {item.format}
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Disclaimer */}
      <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 text-xs text-slate-500 leading-relaxed">
        <strong className="text-slate-700">Disclaimer:</strong> All outputs generated by this tool are for{' '}
        <em>internal evidence organisation purposes only</em>. They do not constitute a regulatory submission,
        regulatory advice, or a guarantee of acceptance by any regulatory authority. Human review by qualified
        regulatory professionals is required before any material is included in an IND, eCTD, or other
        regulatory filing. NAM-derived data should be presented to regulators with full transparency about
        model limitations and context of use.
      </div>
    </div>
  );
}
